import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";

export default function Home() {
  const [query, setQuery] = useState("");
  const [suggestions, setSuggestions] = useState([]);
  const [isDropdownVisible, setIsDropdownVisible] = useState(false);
  const [selectedStories, setSelectedStories] = useState([]);
  const [debouncedQuery, setDebouncedQuery] = useState("");

  useEffect(() => {
    const handler = setTimeout(() => {
      setDebouncedQuery(query);
    }, 500);
    return () => {
      clearTimeout(handler);
    };
  }, [query]);

  useEffect(() => {
    if (debouncedQuery.length >= 3) {
      fetch(`https://hn.algolia.com/api/v1/search?query=${debouncedQuery}`)
        .then((response) => response.json())
        .then((data) => {
          const results = data.hits.map((item) => ({
            title: item.title,
            author: item.author,
            num_comments: item.num_comments,
            points: item.points,
          }));
          setSuggestions(results);
          setIsDropdownVisible(true);
        });
    } else {
      setSuggestions([]);
      setIsDropdownVisible(false);
    }
  }, [debouncedQuery]);

  const handleSelectStory = (story) => {
    setSelectedStories((prevStories) => [...prevStories, story]);
    setQuery("");
    setIsDropdownVisible(false);
  };

  const handleDeleteStory = (index) => {
    setSelectedStories(() => selectedStories.filter((item, i) => i !== index));
  };

  const highlightMatch = (title, query) => {
    if (!query) return title;
    if (!title) return "";
    const regex = new RegExp(`(${query})`, "gi");
    const parts = title?.split(regex);

    return (
      <>
        {parts.map((part, index) =>
          part.toLowerCase() === query.toLowerCase() ? (
            <span key={index} style={{ color: "orange" }}>
              {part}
            </span>
          ) : (
            part
          )
        )}
      </>
    );
  };

  return (
    <>
      <Head>
        <title>Hacker Stories</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.page}`}>
        <main className={styles.main}>
          <h1>Hacker Stories</h1>
          <div>
            <input
              type="text"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Search title"
            />
            {isDropdownVisible && suggestions.length > 0 && (
              <ul>
                {suggestions.map((suggestion, index) => (
                  <li key={index} onClick={() => handleSelectStory(suggestion)}>
                    <h4>{highlightMatch(suggestion.title, debouncedQuery)}</h4>
                    <p>
                      <span>{suggestion.points} points </span> |{" "}
                      <span>{suggestion.author} </span> |{" "}
                      <span>{suggestion.num_comments} comments </span>
                    </p>
                  </li>
                ))}
              </ul>
            )}
          </div>

          {selectedStories.length > 0 && (
            <div>
              <h3>Saved Stories</h3>
              <ul>
                {selectedStories.map((story, index) => (
                  <li key={index}>
                    <h4>{story.title}</h4>
                    <p>
                      <span> {story.points} Points</span> |{" "}
                      <span>{story.author} </span> |{" "}
                      <span> {story.num_comments} comments</span>
                    </p>
                    <button onClick={() => handleDeleteStory(index)}>
                      Delete
                    </button>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </main>
        <footer className={styles.footer}>
          Created By Eleftheria Drakoulakou
        </footer>
      </div>
    </>
  );
}
